server:
  servlet:
    session:
      cookie:
        domain: http://localhost:8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auto_deploy_project?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password:

  redis:
    host: 192.168.8.146
    port: 6379

file:
  upload:
    root: D:/文档/毕业设计/files
    mapping-url: /files

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**/*.xml

deploy:
  docker:
    server-address: http://192.168.8.146:2375/
