server:
  servlet:
    session:
      cookie:
        domain: http://localhost:8080
        admin: http://localhost:8080
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auto_deploy_project?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 172.16.1.243
    port: 6379

file:
  scheme: http
  upload:
    root: D:/文档/毕业设计/files
    mapping-url: /files

jenkins-client:
  host: http://${spring.redis.host}:8080
  admin: exia1771
  password: xww19990712

deploy:
  docker:
    server-address: http://${spring.redis.host}:2375/

logging:
  level:
    github.exia1771.deploy.core.service.jenkins.AbstractJenkinsService: debug
