server:
  port: 8081

spring:
  application:
    name: AUTO_DEPLOY_PROJECT_COMMON

  datasource:
    url: jdbc:mysql://localhost:3306/auto_deploy_project?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password:


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
